Task/pd 4152 helloworld lambda creation
nhsd-exeter/dos-serverless pull request #3
Opened 2021-01-14 12:22 UTC by NagaBushan

Initial draft for serverless framework
A small hello world program on AWS lambda, API Gateway and serverless framework
Implemented unit test using pytest with code coverage tool

2021-01-14 14:01 UTC, timrickwood submitted a review, later dismissed
Good work Naga and thank you for walking me through it too

2021-01-15 09:16 UTC, stefaniuk requested changes

2021-01-15 09:16 UTC, stefaniuk commented on .gitignore
> +application/lambdas/.serverless/*.*
Shall we move `.serverless` and `htmlcov/*.*` to the `application/.gitignore` file? The other python specific files should already be excluded there.

2021-01-15 09:16 UTC, stefaniuk commented on application/READMe.md
> +# DoS Serverless
I wonder if we should move the content of this file to the main README.md?

2021-01-15 13:21 UTC, stefaniuk approved these changes
All good! Thanks

2021-01-15 15:06 UTC, timrickwood approved these changes
I am approving. Not sure if we have to resolve the discussion points too or if those are ignored once we have two approvals

2021-01-22 09:15 UTC, merged